# Generated by Django 5.2 on 2025-05-01 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
    ]
