# Generated by Django 5.2 on 2025-05-08 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_email_alter_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('otp', models.CharField(max_length=6)),
                ('gtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
